services:
  postgres:
    image: postgres:16
    container_name: lesson9-files-module-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-lesson9_files_module}
    ports:
      - "${DB_PORT:-5445}:5432"
    volumes:
      - pgdata_lesson9_files_module:/var/lib/postgresql/data

volumes:
  pgdata_lesson9_files_module:
